plugins {
    id 'com.android.application'
}

android {
    namespace 'com.edigitalsolutions.vehiclekmlog'
    compileSdk 35

    defaultConfig {
        applicationId 'com.edigitalsolutions.vehiclekmlog'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
